[build]
  command = "npm install && npx nest build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-optional"

[[redirects]]
  from = "/*"
  to = "/backend/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/backend/docs"
  status = 302

[dev]
  command = "npm run start:dev"
  port = 3000
  targetPort = 3000
  framework = "nestjs"
